### ISSUE TITLE
Module isnt starting

### ISSUE THREAD

**Issue by microdimmer** [PowerBroker2/DFPlayerMini_Fast#1]
Using you librarry, by default module playing nothing. But if using https://github.com/DFRobot/DFRobotDFPlayerMini library and changing to yours without powering off module, all working good. It seems to me than module isnt starting on initialisation. How to initialize module properly? 
Thank you.

**Comment by PowerBroker2** [comment]
It's impossible to know without seeing your code. Can you post it?
