### ISSUE TITLE
Functions did not work

### ISSUE THREAD

**Issue by MarphXL** [PowerBroker2/DFPlayerMini_Fast#20]
Can you please explain how I can get the Volume or Number of files at SD-Card? I ever get a 0. It would be superb if you add these lines to your example if the functions are working. Thanks for that library!

**Comment by MarphXL** [comment]
I double-checked all connections and try the original DFRobot-library and this works. Switching back to DFPlayerMini_Fast and the readings from serial connection didn't work. Maybe a protocol-problem in your library?

**Comment by PowerBroker2** [comment]
Try [release 1.1.10](https://github.com/PowerBroker2/DFPlayerMini_Fast/releases/tag/1.1.10)

**Comment by MarphXL** [comment]
how I can get the Volume or Number of files at SD-Card?

**Comment by PowerBroker2** [comment]
Why do you need to query for volume? Since your sketch sets the volume, it should be able to remember what level was set. The number of files can be found using `numSdTracks()`
