### ISSUE TITLE
Is randomAll supposed to pull from the advert folder in addition to the mp3 folder?

### ISSUE THREAD

**Issue by dancota** [PowerBroker2/DFPlayerMini_Fast#21]
Is the randomAll supposed to pull from the advert folder? Is so is there a  way to restrict a RandomCall to a specific folder?

**Comment by PowerBroker2** [comment]
From the documentation:

> This command is used to randomly play sound files in the storage device according to physical sequence and no matter if there is a folder or not in the device. The first sound file that is conducted to be played is the first one in the device.
