### ISSUE TITLE
Read files from SPI Flash

### ISSUE THREAD

**Issue by eugjr** [PowerBroker2/DFPlayerMini_Fast#25]
Hi, first, thanks for the nice work done on the library. I've tested it with the DFPlayer and your library worked better than the original one.

I have a project in mind, that needs do fit in a very narrow piece, where the Dfplayer wont fit. 

Do you think your library could be able to read the wav files from a SPI Flash (like winbond chips)? I'm looking for various libraries and projects using arduino and struggling to get it running nice.

Thanks in advance

**Comment by PowerBroker2** [comment]
The lib is used to automate the serial communication protocol used by the DFPlayer and doesn't touch SPI directly. Unfortunately, that means this lib won't be useful for you
