### ISSUE TITLE
What' the purpose of startDAC() and stopDAC() methods?

### ISSUE THREAD

**Issue by StarterCraft** [PowerBroker2/DFPlayerMini_Fast#27]
If I will use an amplifier (`PAM8406`, for example) with the `DFPlayer`. I'll use the `DAC_R` pin (in mono mode) instead of `SPK+` and `SPK-` pins. 
What's the difference between running the `DFPlayer` with an amplifier without calling `startDAC()` in the code and running the `DFPlayer` with an amplifier with calling `startDAC()` in the code?

**Comment by PowerBroker2** [comment]
`startDAC()` enables the DAC and `stopDAC()` disables it, however, the DAC is enabled by default on power-up, so you're good to use the `SPK+-` pins without these functions if you want
