### ISSUE TITLE
Lag and sound cut produced after library update

### ISSUE THREAD

**Issue by tsctrl** [PowerBroker2/DFPlayerMini_Fast#30]
Hi @PowerBroker2 ,

I encounter lagged and sound cut on the latest lib update running on esp32. The player seems to stop from doing its current task when getting other  play request concurrently. Not have this issue on the previous version.
I have add timers to reduce the call, do the pin busy check but still getting the issue once the timer countdown ends.

Thank you

**Comment by PowerBroker2** [comment]
Can you post a small sketch that reproduces the issue?

**Comment by tsctrl** [comment]
will do and investigate further. for now, i revert the direct parseFeedback() call to the previous getStatus() function and the lag is gone.

thank you
