### ISSUE TITLE
loop a track in a folder

### ISSUE THREAD

**Issue by anzbert** [PowerBroker2/DFPlayerMini_Fast#32]
is it possible to loop a track inside a folder?

what i've tried is this and it didnt work:

> mp3.playFolder(1, 2);
> mp3.startRepeat();

i dont think i can use the mp3.loop() function with a folder.

thanks so much for the help and for the great library!!

**Comment by anzbert** [comment]
i found a workaround. this seems to do the trick:

        mp3.playFolder(1, 2);
        int num = mp3.currentSdTrack();
        mp3.loop(num);

**Comment by PowerBroker2** [comment]
Looping a track in a folder isn't something I've thought to do - I'm glad you figured it out and thanks for sharing the solution!
