### ISSUE TITLE
Question: how to check if the dfplayer was initialized?

### ISSUE THREAD

**Issue by tsctrl** [PowerBroker2/DFPlayerMini_Fast#33]
i have a function that call dFPlayerMini.play() directly. if the df was not initialize using begin() it will trigger panic exception and the mcu was restarted.

how to check if df player was initialized? simple check without need to provide the parameters in begin?

**Comment by PowerBroker2** [comment]
If you call `begin()` properly with the correct arguments and your wiring is correct, it will always initialize correctly. Even if the MP3 player isn't initialized correctly for whatever reason, it would not cause a CPU panic on your MCU. Can you post your code in tags plus the error?

**Comment by tsctrl** [comment]
solve this by if instance null checking
