### ISSUE TITLE
Library update effors

### ISSUE THREAD

**Issue by ejmorgan55** [PowerBroker2/DFPlayerMini_Fast#34]
Just updated the library on the INO and I now get the following error: Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Nano, ATmega328P (Old Bootloader)"

C:\Users\EJMOR\AppData\Local\Temp\cc1JJQ42.ltrans0.ltrans.o: In function `setup':

C:\Users\EJMOR\OneDrive\Documents\Arduino\Gideon/Gideon.ino:51: undefined reference to `DFPlayerMini_Fast::begin(Stream&, bool, unsigned long)'

collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board Arduino Nano.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by PowerBroker2** [comment]
What version of the library are you using? Please post your sketch in full and in tags
