### ISSUE TITLE
Start Track at Certain Time

### ISSUE THREAD

**Issue by harry90** [PowerBroker2/DFPlayerMini_Fast#39]
Does the lib have functions to start a track at a certain time and play a track for a certain time?

playTrackAt(5, 3500); // Start Track 5 at 3500ms
playTrackAt(5, 3500, 3000); // Start Track 5 at 3500ms and play it for 3000ms

**Comment by PowerBroker2** [comment]
Nope, this is a limitation of the chip used by the DFPlayerMini. Check the datasheet in the lib's "extras" folder
