### ISSUE TITLE
Volume won't change

### ISSUE THREAD

**Issue by ashleycox** [PowerBroker2/DFPlayerMini_Fast#42]
I'm using the library with a DFPlayer Mini module and an Arduino Nano. It is a clone, but unlike some does respond to serial commands. I am not able to lower the volume using the simple sketch below. I tried adding a 10MS delay before the volume change as mentioned in one of the other issues concerning this, but that didn't work. The module responds to other commands just fine. Any ideas? The module works fine with other libraries including the official DFRobot library. Here is my serial monitor output:

```
Setting volume to 4
Sent Stack:
7E FF 6 6 0 0 4 FE F1 EF

playtrack 1
Sent Stack:
7E FF 6 3 0 0 1 FE F7 EF
```

And the code:

```C++
#include <DFPlayerMini_Fast.h>
#include <SoftwareSerial.h>
SoftwareSerial mySerial(10, 11); // RX, TX

DFPlayerMini_Fast myMP3;

void setup()
{
  Serial.begin(9400);

  mySerial.begin(9600);
  myMP3.begin(mySerial, true);
  
  Serial.println("Setting volume to 4");
delay(10);
myMP3.volume(4);
  
  Serial.println("playtrack 1");
  myMP3.play(1);
}
```

**Comment by adrienluitot** [comment]
Maybe try adding a bigger delay ?
Or try changing the volume in the loop, just to see if sending the volume delayed might work.

**Comment by ashleycox** [comment]
Thanks for both suggestions, neither worked unfortunately.

**Comment by adrienluitot** [comment]
That's strange, it works with me.
Are you sure volume didn't change? You can check with the function `.currentVolume()`.

**Comment by ashleycox** [comment]
Interesting. CurrentVolume returns 30 regardless of how / when the volume is set. Works fine with the DFRobot library and all other functions are working here so it is baffling.

**Comment by adrienluitot** [comment]
That's pretty strange. :thinking:

**Comment by PowerBroker2** [comment]
This works perfectly for me:

```C++
#include <DFPlayerMini_Fast.h>

#if !defined(UBRR1H)
#include <SoftwareSerial.h>
SoftwareSerial mySerial(10, 11); // RX, TX
#endif

DFPlayerMini_Fast myMP3;

void setup()
{
  Serial.begin(115200);

#if !defined(UBRR1H)
  mySerial.begin(9600);
  myMP3.begin(mySerial, true);
#else
  Serial1.begin(9600);
  myMP3.begin(Serial1, true);
#endif

  delay(1000);
  
  Serial.println("Setting volume to 4");
  myMP3.volume(4);

  delay(10);
  
  Serial.println("Looping track 1");
  myMP3.play(1);
}

void loop()
{
  
}
```

**Comment by ashleycox** [comment]
Still not working here, it still plays at max volume even with the exact code you posted above. Any other ideas? Could FireTimer be the issue?

**Comment by ashleycox** [comment]
OK, some further experimentation and I've got it to work, sort of. It seems I need at least a 50MS delay before MP3.play(1), or the volume change doesn't happen. The code below works. Any ideas why this might be, and how I could fix it without adding this delay?

```
#include <SoftwareSerial.h>
#include <DFPlayerMini_Fast.h>
SoftwareSerial mySerial(10, 11); // RX, TX
DFPlayerMini_Fast myMP3;

void setup()
{
  Serial.begin(9400);
    mySerial.begin(9600);

  myMP3.begin(mySerial);
  
  Serial.println("Setting volume to 4");
  myMP3.volume(4);

  Serial.println("Looping track 1");
delay(50);
myMP3.play(1);


}

void loop()
{
  
}
```

**Comment by PowerBroker2** [comment]
If a delay fixes it, the problem is most likely the firmware on your DFPlayerMini clone
