### ISSUE TITLE
No Sound 

### ISSUE THREAD

**Issue by B3nj000** [PowerBroker2/DFPlayerMini_Fast#45]
Hi, I wantet  to use the Library for my DfPlayer Mini but there is no Sound coming out. The wiring is correct, I formatet the SD Card and I named the folder and the Tracks correctly. When  I try  to use  the standart DFRobot Library ist says: Check the Connection, Insert the SD Card. I cant figure  it out. I tried to find it  out myself but after a month its time to get some help ^^

**Comment by PowerBroker2** [comment]
That's either an issue with how you're powering the device, how you formatted the SD card/it's contents, or the MP3 chip itself, not the library.

This might help: [link](https://forum.arduino.cc/t/dfplayer-mini-didnt-working-anymore/526437/15)
