### ISSUE TITLE
DFPlayer mini volume level in all new chipsets

### ISSUE THREAD

**Issue by supermandt** [PowerBroker2/DFPlayerMini_Fast#49]
Hi PowerBroker, I just wanted to share what I figured out with the volume setting.  With all these new chipsets coming out, I was unable to set the volume level in software and which you helped me work on a few months ago.  I solved the issue, just increased the delay after the mp3.begin() in the setup  from my 20ms to 1000 and now the volume is working again!    Just wanted to share and say thank you for all your help too!

void setup() {
  Serial.begin(9600);
  mySerial.begin(9600);
  myMP3.begin(mySerial);
  delay(1000);
  myMP3.volume(SPEAKER_VOLUME);
}

**Comment by PowerBroker2** [comment]
Thanks for sharing! What chipsets have you tested this with?

**Comment by supermandt** [comment]
My pleasure!
All MP3 DFplayers seem to work except the MP3-TF10P(something like that)  labeled ones.

**Comment by agfaps** [comment]
Hi,
From library version 1.1.0 I have also added delay about 1000ms after begin() and it works well with many chips.
And if this is new or not, In my case, if I call currentSdTrack with timeout 200ms(not default 100ms), the return value is -1. After I increase the threshold to respond to 500ms, then return value is valid.
Actually I want to create new issue but I just post it here.
Hope it will help another person who also use this amazing library.
If you ask which chip? I have 8 different chips of it. From YX5200, GD3200B, MH2024K-24SS (24 pin), MH2024K-16SS (16 pin), and JL series (AC21xx, AA20xx, AS20xx, AA19xx) and not every chip has the same characteristics.
Oh btw, some chips only works (even some chip not all command works) when there's no checksum in command(removing 2 bytes). most can process command with or without checksum.
Thank you.
