### ISSUE TITLE
Provide example of querying commands

### ISSUE THREAD

**Issue by nbraynor** [PowerBroker2/DFPlayerMini_Fast#5]
Would it be possible to provide an example of the query commands? How to use query, getStatus, parseFeedback, printStack?

Thanks for the awesome library. I tried using the DFRobots library, but I couldn't get it to reliably detect when a track had stopped. I'm hoping this library will be able to. #

**Comment by PowerBroker2** [comment]
This should do the trick. Nice and simple:

```
#include <SoftwareSerial.h>
#include <DFPlayerMini_Fast.h>

SoftwareSerial mySerial(10, 11); // RX, TX
DFPlayerMini_Fast myMP3;

void setup()
{
  Serial.begin(115200);
  mySerial.begin(9600);

  myMP3.begin(mySerial);
  
  Serial.println("Setting volume to max");
  myMP3.volume(30);
  delay(20);
  
  Serial.println("Start track 1");
  myMP3.play(1);

  while(myMP3.isPlaying());

  Serial.println("Track 1 done");
}

void loop()
{
  //do nothing
}
```

You can also call `uint16_t trackNum = myMP3.currentSdTrack();` to find the current track number (if it's currently playing)
