### ISSUE TITLE
return -1 in numSdTracks()

### ISSUE THREAD

**Issue by filipedias1994** [PowerBroker2/DFPlayerMini_Fast#50]
Hi!

I'm trying to play a track but when I start the program it returns "-1" in the number of tracks. On the sdcard is the folder "mp3" with the files renamed to "0001.mp3, 0002.mp3" and so on.

Using the original library(https://github.com/DFRobot/DFRobotDFPlayerMini) I get the same value as "-1" but as I go forward the tracks are played.

Does anyone know what can it be?

```C++
#include <DFPlayerMini_Fast.h>
#include <Arduino.h>


HardwareSerial mySerial(1);
DFPlayerMini_Fast myMP3;

void setup()
{
  Serial.begin(115200);

#if !defined(UBRR1H)
  mySerial.begin(9600, SERIAL_8N1, 18, 19);
  myMP3.begin(mySerial, true);
#else
  Serial1.begin(9600);
  myMP3.begin(Serial1, true);
#endif
  delay(1000);
  myMP3.setTimeout(1000);
  Serial.print(F("File found in SD: "));
  Serial.println(myMP3.numSdTracks());
  Serial.println("Setting volume to max");
  myMP3.volume(10);
  myMP3.playFromMP3Folder(1);
  delay(5000);
  Serial.println("Looping track 1");
  myMP3.loop(1);
}

void loop()
{
  char choice = Serial.read();
    if (choice == 'a')
  {
    Serial.println("---Advance---");
    myMP3.playNext();
    Serial.print(myMP3.currentSdTrack());
    Serial.print('/');
    Serial.println(myMP3.numSdTracks());
  }
}
```

**Comment by PowerBroker2** [comment]
Your code is working fine with my Mega and DFPlayerMini - can't replicate the issue. Make sure you're using the right serial port and your Arduino's TX is wired to the DFPlayer's RX etc.
