### ISSUE TITLE
Thank-you PowerBroker2! - Im using this to send DTMF/touch tones

### ISSUE THREAD

**Issue by Cloolalang** [PowerBroker2/DFPlayerMini_Fast#53]
Huge thanks for you work on this.
I have used your library for quickly creating a DTMF encoder/generator. Its fast enough to be able to play the tones I need for my IOT over radio project with the decoder module MT8870.
I am using tones downloaded from here:
https://www.audiocheck.net/audiocheck_dtmf.php
and playing 8K wav files perfectly with the DFplayer module.
And off course I have the added option to play voice announcements and other control tones such as ANI and maybe even 1200 bell packets..

**Comment by Cloolalang** [comment]
.

**Comment by PowerBroker2** [comment]
That's so cool! Thanks for letting me know!
