### ISSUE TITLE
DUDE I GET ANGER FOR THAT

### ISSUE THREAD

**Issue by Lorenzo228295** [PowerBroker2/DFPlayerMini_Fast#71]
THE HELL >;( THIS IS NOT WORKING, BECAUSE OF C:\Users\Lorenzo\Documents\Arduino\libraries\DFPlayerMini_Fast\src/DFPlayerMini_Fast.h:22:23: fatal error: FireTimer.h: No such file or directory

READ THIS ERROR BECAUSE I CANT DO THIS ANYMORE FUCK

**Comment by derniwi** [comment]
Hi,
follow the link in the "README.MD":
[> See the documentation <](https://powerbroker2.github.io/DFPlayerMini_Fast/html/index.html)
There is a comment:
Dependencies
This library depends on [FireTimer.h](https://github.com/PowerBroker2/FireTimer) being present on your system. Please make sure you have installed the latest version before using this library.

Than you can compile...

Regards
Nils
